const en = {
  "updates.title": "App & CLI updates",
  "updates.app": "Desktop app",
  "updates.cli": "Supercharge CLI",
  "updates.notChecked": "Not checked",
  "updates.current": "Up to date",
  "updates.notPublished": "No desktop release published",
  "updates.available": "Update available",
  "updates.downloading": "Downloading…",
  "updates.downloaded": "Downloaded · restart to apply",
  "updates.installing": "Installing…",
  "updates.installed": "Installed · restart to use",
  "updates.manual": "Manual installation required",
  "updates.failed": "Update failed",
  "updates.cliMissing": "Supercharge CLI is not installed.",
  "updates.cliCheckUnavailable": "This CLI does not support update checks.",
  "updates.restartReady": "Updates ready to restart",
  "updates.checking": "Checking both versions…",
  "updates.restartHint": "Restart when you are ready. Your current chats keep running until then.",
  "updates.description": "Updates only newer versions of the app and CLI. Verified downloads are kept for reuse.",
  "updates.check": "Check app & CLI",
  "updates.updateBoth": "Update app & CLI",
  "updates.restart": "Restart to use updates",
  "updates.restarting": "Restarting…",
  "updates.openDownload": "Download app installer",
  "updates.confirmTitle": "Restart to use updates?",
  "updates.confirmBody": "The downloaded app update will be applied and Supercharge will restart. Running agent tasks will stop; saved chats are kept.",
} as const;

type Updates = Record<keyof typeof en, string>;
export const updateMessages = {
  en,
  de: {
    "updates.title": "App- und CLI-Updates", "updates.app": "Desktop-App", "updates.cli": "Supercharge CLI", "updates.notChecked": "Nicht geprüft", "updates.current": "Aktuell", "updates.notPublished": "Keine Desktop-Version veröffentlicht", "updates.available": "Update verfügbar", "updates.downloading": "Wird heruntergeladen…", "updates.downloaded": "Heruntergeladen · Neustart zum Anwenden", "updates.installing": "Wird installiert…", "updates.installed": "Installiert · Neustart zur Nutzung", "updates.manual": "Manuelle Installation erforderlich", "updates.failed": "Update fehlgeschlagen", "updates.restartReady": "Updates bereit zum Neustart", "updates.checking": "Beide Versionen werden geprüft…", "updates.restartHint": "Starten Sie neu, wenn Sie bereit sind. Ihre Chats laufen bis dahin weiter.", "updates.description": "Aktualisiert nur auf neuere App- und CLI-Versionen. Geprüfte Downloads werden wiederverwendet.", "updates.check": "App und CLI prüfen", "updates.updateBoth": "App und CLI aktualisieren", "updates.restart": "Neustarten und Updates nutzen", "updates.restarting": "Neustart…", "updates.openDownload": "App-Installationsdatei herunterladen", "updates.confirmTitle": "Neustarten und Updates nutzen?", "updates.confirmBody": "Das heruntergeladene App-Update wird angewendet und Supercharge neu gestartet. Laufende Agent-Aufgaben werden beendet; gespeicherte Chats bleiben erhalten.",
    "updates.cliMissing": "Supercharge CLI ist nicht installiert.",
    "updates.cliCheckUnavailable": "Diese CLI unterstützt keine Update-Prüfung.",
  },
  es: {
    "updates.title": "Actualizaciones de app y CLI", "updates.app": "Aplicación de escritorio", "updates.cli": "Supercharge CLI", "updates.notChecked": "Sin comprobar", "updates.current": "Actualizado", "updates.notPublished": "No hay versión de escritorio publicada", "updates.available": "Actualización disponible", "updates.downloading": "Descargando…", "updates.downloaded": "Descargado · reinicia para aplicar", "updates.installing": "Instalando…", "updates.installed": "Instalado · reinicia para usar", "updates.manual": "Requiere instalación manual", "updates.failed": "Error de actualización", "updates.restartReady": "Actualizaciones listas para reiniciar", "updates.checking": "Comprobando ambas versiones…", "updates.restartHint": "Reinicia cuando quieras. Tus chats siguen funcionando hasta entonces.", "updates.description": "Solo actualiza a versiones más nuevas de la app y la CLI. Conserva las descargas verificadas para reutilizarlas.", "updates.check": "Comprobar app y CLI", "updates.updateBoth": "Actualizar app y CLI", "updates.restart": "Reiniciar para usar actualizaciones", "updates.restarting": "Reiniciando…", "updates.openDownload": "Descargar instalador de la app", "updates.confirmTitle": "¿Reiniciar para usar las actualizaciones?", "updates.confirmBody": "Se aplicará la actualización descargada y Supercharge se reiniciará. Las tareas de agentes en curso se detendrán; los chats guardados se conservarán.",
    "updates.cliMissing": "Supercharge CLI no está instalado.",
    "updates.cliCheckUnavailable": "Esta CLI no admite la comprobación de actualizaciones.",
  },
  fil: {
    "updates.title": "Mga update ng app at CLI", "updates.app": "Desktop app", "updates.cli": "Supercharge CLI", "updates.notChecked": "Hindi pa nasuri", "updates.current": "Pinakabagong bersyon", "updates.notPublished": "Wala pang inilabas na desktop bersyon", "updates.available": "May bagong update", "updates.downloading": "Dina-download…", "updates.downloaded": "Na-download · i-restart para ilapat", "updates.installing": "Ini-install…", "updates.installed": "Na-install · i-restart para gamitin", "updates.manual": "Kailangang manu-manong i-install", "updates.failed": "Nabigo ang update", "updates.restartReady": "Handa nang i-restart para sa mga update", "updates.checking": "Sinusuri ang dalawang bersyon…", "updates.restartHint": "I-restart kapag handa ka na. Patuloy munang tatakbo ang mga chat mo.", "updates.description": "Mas bagong bersyon lang ng app at CLI ang ina-update. Itinatago ang mga na-verify na download para magamit muli.", "updates.check": "Suriin ang app at CLI", "updates.updateBoth": "I-update ang app at CLI", "updates.restart": "I-restart para gamitin ang mga update", "updates.restarting": "Nagre-restart…", "updates.openDownload": "I-download ang installer ng app", "updates.confirmTitle": "I-restart para gamitin ang mga update?", "updates.confirmBody": "Ilalapat ang na-download na update at magre-restart ang Supercharge. Hihinto ang kasalukuyang mga gawain ng agent; mananatili ang mga naka-save na chat.",
    "updates.cliMissing": "Hindi naka-install ang Supercharge CLI.",
    "updates.cliCheckUnavailable": "Hindi sinusuportahan ng CLI ang pagsusuri ng update.",
  },
  fr: {
    "updates.title": "Mises à jour de l’app et de la CLI", "updates.app": "Application de bureau", "updates.cli": "Supercharge CLI", "updates.notChecked": "Non vérifié", "updates.current": "À jour", "updates.notPublished": "Aucune version de bureau publiée", "updates.available": "Mise à jour disponible", "updates.downloading": "Téléchargement…", "updates.downloaded": "Téléchargée · redémarrer pour appliquer", "updates.installing": "Installation…", "updates.installed": "Installée · redémarrer pour utiliser", "updates.manual": "Installation manuelle requise", "updates.failed": "Échec de la mise à jour", "updates.restartReady": "Mises à jour prêtes au redémarrage", "updates.checking": "Vérification des deux versions…", "updates.restartHint": "Redémarrez quand vous le souhaitez. Vos discussions continuent jusque-là.", "updates.description": "Installe uniquement les versions plus récentes de l’app et de la CLI. Les téléchargements vérifiés sont conservés pour être réutilisés.", "updates.check": "Vérifier l’app et la CLI", "updates.updateBoth": "Mettre à jour l’app et la CLI", "updates.restart": "Redémarrer pour utiliser les mises à jour", "updates.restarting": "Redémarrage…", "updates.openDownload": "Télécharger le programme d’installation", "updates.confirmTitle": "Redémarrer pour utiliser les mises à jour ?", "updates.confirmBody": "La mise à jour téléchargée sera appliquée et Supercharge redémarrera. Les tâches des agents en cours s’arrêteront ; les discussions enregistrées seront conservées.",
    "updates.cliMissing": "Supercharge CLI n’est pas installée.",
    "updates.cliCheckUnavailable": "Cette CLI ne prend pas en charge la vérification des mises à jour.",
  },
  id: {
    "updates.title": "Pembaruan aplikasi & CLI", "updates.app": "Aplikasi desktop", "updates.cli": "Supercharge CLI", "updates.notChecked": "Belum diperiksa", "updates.current": "Sudah terbaru", "updates.notPublished": "Belum ada rilis desktop", "updates.available": "Pembaruan tersedia", "updates.downloading": "Mengunduh…", "updates.downloaded": "Terunduh · mulai ulang untuk menerapkan", "updates.installing": "Memasang…", "updates.installed": "Terpasang · mulai ulang untuk menggunakan", "updates.manual": "Perlu pemasangan manual", "updates.failed": "Pembaruan gagal", "updates.restartReady": "Pembaruan siap, mulai ulang", "updates.checking": "Memeriksa kedua versi…", "updates.restartHint": "Mulai ulang saat Anda siap. Obrolan tetap berjalan hingga saat itu.", "updates.description": "Hanya memperbarui aplikasi dan CLI ke versi lebih baru. Unduhan terverifikasi disimpan untuk digunakan kembali.", "updates.check": "Periksa aplikasi & CLI", "updates.updateBoth": "Perbarui aplikasi & CLI", "updates.restart": "Mulai ulang untuk menggunakan pembaruan", "updates.restarting": "Memulai ulang…", "updates.openDownload": "Unduh pemasang aplikasi", "updates.confirmTitle": "Mulai ulang untuk menggunakan pembaruan?", "updates.confirmBody": "Pembaruan aplikasi yang diunduh akan diterapkan dan Supercharge dimulai ulang. Tugas agen yang berjalan akan berhenti; obrolan tersimpan tetap disimpan.",
    "updates.cliMissing": "Supercharge CLI belum terpasang.",
    "updates.cliCheckUnavailable": "CLI ini tidak mendukung pemeriksaan pembaruan.",
  },
  it: {
    "updates.title": "Aggiornamenti app e CLI", "updates.app": "App desktop", "updates.cli": "Supercharge CLI", "updates.notChecked": "Non verificato", "updates.current": "Aggiornato", "updates.notPublished": "Nessuna versione desktop pubblicata", "updates.available": "Aggiornamento disponibile", "updates.downloading": "Download…", "updates.downloaded": "Scaricato · riavvia per applicare", "updates.installing": "Installazione…", "updates.installed": "Installato · riavvia per usare", "updates.manual": "Installazione manuale richiesta", "updates.failed": "Aggiornamento non riuscito", "updates.restartReady": "Aggiornamenti pronti al riavvio", "updates.checking": "Verifica di entrambe le versioni…", "updates.restartHint": "Riavvia quando vuoi. Le chat continuano a funzionare fino ad allora.", "updates.description": "Aggiorna solo a versioni più recenti di app e CLI. I download verificati vengono conservati per il riutilizzo.", "updates.check": "Verifica app e CLI", "updates.updateBoth": "Aggiorna app e CLI", "updates.restart": "Riavvia per usare gli aggiornamenti", "updates.restarting": "Riavvio…", "updates.openDownload": "Scarica il programma di installazione", "updates.confirmTitle": "Riavviare per usare gli aggiornamenti?", "updates.confirmBody": "Verrà applicato l’aggiornamento scaricato e Supercharge si riavvierà. Le attività degli agenti in corso si fermeranno; le chat salvate verranno conservate.",
    "updates.cliMissing": "Supercharge CLI non è installata.",
    "updates.cliCheckUnavailable": "Questa CLI non supporta il controllo degli aggiornamenti.",
  },
  ja: {
    "updates.title": "アプリとCLIの更新", "updates.app": "デスクトップアプリ", "updates.cli": "Supercharge CLI", "updates.notChecked": "未確認", "updates.current": "最新です", "updates.notPublished": "デスクトップ版は未公開です", "updates.available": "更新があります", "updates.downloading": "ダウンロード中…", "updates.downloaded": "ダウンロード済み・再起動で適用", "updates.installing": "インストール中…", "updates.installed": "インストール済み・再起動で使用", "updates.manual": "手動インストールが必要です", "updates.failed": "更新に失敗しました", "updates.restartReady": "再起動で更新を適用できます", "updates.checking": "両方のバージョンを確認中…", "updates.restartHint": "準備ができたら再起動してください。それまではチャットを継続できます。", "updates.description": "アプリとCLIは新しいバージョンのみ更新します。検証済みのダウンロードは再利用します。", "updates.check": "アプリとCLIを確認", "updates.updateBoth": "アプリとCLIを更新", "updates.restart": "再起動して更新を使用", "updates.restarting": "再起動中…", "updates.openDownload": "アプリのインストーラーをダウンロード", "updates.confirmTitle": "再起動して更新を使用しますか？", "updates.confirmBody": "ダウンロード済みの更新を適用し、Superchargeを再起動します。実行中のエージェントのタスクは停止しますが、保存済みのチャットは保持されます。",
    "updates.cliMissing": "Supercharge CLIがインストールされていません。",
    "updates.cliCheckUnavailable": "このCLIは更新の確認に対応していません。",
  },
  ko: {
    "updates.title": "앱 및 CLI 업데이트", "updates.app": "데스크톱 앱", "updates.cli": "Supercharge CLI", "updates.notChecked": "확인 전", "updates.current": "최신 버전", "updates.notPublished": "게시된 데스크톱 버전 없음", "updates.available": "업데이트 가능", "updates.downloading": "다운로드 중…", "updates.downloaded": "다운로드 완료 · 재시작하여 적용", "updates.installing": "설치 중…", "updates.installed": "설치 완료 · 재시작하여 사용", "updates.manual": "수동 설치 필요", "updates.failed": "업데이트 실패", "updates.restartReady": "업데이트 준비 완료", "updates.checking": "두 버전 확인 중…", "updates.restartHint": "준비되면 재시작하세요. 그때까지 현재 채팅은 계속 실행됩니다.", "updates.description": "앱과 CLI의 더 새로운 버전만 업데이트합니다. 검증된 다운로드는 재사용합니다.", "updates.check": "앱 및 CLI 확인", "updates.updateBoth": "앱 및 CLI 업데이트", "updates.restart": "재시작하여 업데이트 사용", "updates.restarting": "재시작 중…", "updates.openDownload": "앱 설치 파일 다운로드", "updates.confirmTitle": "재시작하여 업데이트를 사용할까요?", "updates.confirmBody": "다운로드한 앱 업데이트를 적용하고 Supercharge를 재시작합니다. 실행 중인 에이전트 작업은 중지되며 저장된 채팅은 유지됩니다.",
    "updates.cliMissing": "Supercharge CLI가 설치되어 있지 않습니다.",
    "updates.cliCheckUnavailable": "이 CLI는 업데이트 확인을 지원하지 않습니다.",
  },
  "pt-BR": {
    "updates.title": "Atualizações do app e da CLI", "updates.app": "Aplicativo desktop", "updates.cli": "Supercharge CLI", "updates.notChecked": "Não verificado", "updates.current": "Atualizado", "updates.notPublished": "Nenhuma versão desktop publicada", "updates.available": "Atualização disponível", "updates.downloading": "Baixando…", "updates.downloaded": "Baixado · reinicie para aplicar", "updates.installing": "Instalando…", "updates.installed": "Instalado · reinicie para usar", "updates.manual": "Instalação manual necessária", "updates.failed": "Falha na atualização", "updates.restartReady": "Atualizações prontas para reiniciar", "updates.checking": "Verificando as duas versões…", "updates.restartHint": "Reinicie quando quiser. Seus chats continuam funcionando até lá.", "updates.description": "Atualiza apenas para versões mais novas do app e da CLI. Downloads verificados são mantidos para reutilização.", "updates.check": "Verificar app e CLI", "updates.updateBoth": "Atualizar app e CLI", "updates.restart": "Reiniciar para usar atualizações", "updates.restarting": "Reiniciando…", "updates.openDownload": "Baixar instalador do app", "updates.confirmTitle": "Reiniciar para usar as atualizações?", "updates.confirmBody": "A atualização baixada será aplicada e o Supercharge será reiniciado. As tarefas dos agentes em execução serão interrompidas; os chats salvos serão preservados.",
    "updates.cliMissing": "A Supercharge CLI não está instalada.",
    "updates.cliCheckUnavailable": "Esta CLI não permite verificar atualizações.",
  },
  ru: {
    "updates.title": "Обновления приложения и CLI", "updates.app": "Приложение", "updates.cli": "Supercharge CLI", "updates.notChecked": "Не проверено", "updates.current": "Актуальная версия", "updates.notPublished": "Релиз приложения ещё не опубликован", "updates.available": "Доступно обновление", "updates.downloading": "Скачивание…", "updates.downloaded": "Скачано · перезапустите для применения", "updates.installing": "Установка…", "updates.installed": "Установлено · перезапустите для использования", "updates.manual": "Нужна ручная установка", "updates.failed": "Ошибка обновления", "updates.restartReady": "Обновления готовы к перезапуску", "updates.checking": "Проверка обеих версий…", "updates.restartHint": "Перезапустите, когда будете готовы. До этого чаты продолжают работать.", "updates.description": "Обновляет приложение и CLI только до более новых версий. Проверенные загрузки сохраняются для повторного использования.", "updates.check": "Проверить приложение и CLI", "updates.updateBoth": "Обновить приложение и CLI", "updates.restart": "Перезапустить для применения обновлений", "updates.restarting": "Перезапуск…", "updates.openDownload": "Скачать установщик приложения", "updates.confirmTitle": "Перезапустить для применения обновлений?", "updates.confirmBody": "Скачанное обновление будет применено, и Supercharge перезапустится. Выполняемые задачи агентов остановятся; сохранённые чаты останутся.",
    "updates.cliMissing": "Supercharge CLI не установлена.",
    "updates.cliCheckUnavailable": "Эта CLI не поддерживает проверку обновлений.",
  },
  ta: {
    "updates.title": "செயலி மற்றும் CLI புதுப்பிப்புகள்", "updates.app": "டெஸ்க்டாப் செயலி", "updates.cli": "Supercharge CLI", "updates.notChecked": "சரிபார்க்கப்படவில்லை", "updates.current": "சமீபத்திய பதிப்பு", "updates.notPublished": "டெஸ்க்டாப் பதிப்பு இன்னும் வெளியிடப்படவில்லை", "updates.available": "புதுப்பிப்பு உள்ளது", "updates.downloading": "பதிவிறக்குகிறது…", "updates.downloaded": "பதிவிறங்கியது · பயன்படுத்த மறுதொடக்கம் செய்யவும்", "updates.installing": "நிறுவுகிறது…", "updates.installed": "நிறுவப்பட்டது · பயன்படுத்த மறுதொடக்கம் செய்யவும்", "updates.manual": "கைமுறை நிறுவல் தேவை", "updates.failed": "புதுப்பிப்பு தோல்வியடைந்தது", "updates.restartReady": "புதுப்பிப்புகள் மறுதொடக்கத்திற்குத் தயார்", "updates.checking": "இரு பதிப்புகளையும் சரிபார்க்கிறது…", "updates.restartHint": "தயாரானதும் மறுதொடக்கம் செய்யவும். அதுவரை உங்கள் உரையாடல்கள் தொடர்ந்து இயங்கும்.", "updates.description": "செயலி மற்றும் CLI-யின் புதிய பதிப்புகளை மட்டும் புதுப்பிக்கும். சரிபார்க்கப்பட்ட பதிவிறக்கங்கள் மீண்டும் பயன்படுத்தச் சேமிக்கப்படும்.", "updates.check": "செயலி மற்றும் CLI-ஐச் சரிபார்", "updates.updateBoth": "செயலி மற்றும் CLI-ஐப் புதுப்பி", "updates.restart": "புதுப்பிப்புகளைப் பயன்படுத்த மறுதொடக்கம் செய்", "updates.restarting": "மறுதொடக்கம் செய்கிறது…", "updates.openDownload": "செயலி நிறுவியைப் பதிவிறக்கு", "updates.confirmTitle": "புதுப்பிப்புகளைப் பயன்படுத்த மறுதொடக்கம் செய்யவா?", "updates.confirmBody": "பதிவிறக்கிய புதுப்பிப்பு பயன்படுத்தப்பட்டு Supercharge மறுதொடக்கம் செய்யப்படும். இயங்கும் முகவர் பணிகள் நிறுத்தப்படும்; சேமித்த உரையாடல்கள் தக்கவைக்கப்படும்.",
    "updates.cliMissing": "Supercharge CLI நிறுவப்படவில்லை.",
    "updates.cliCheckUnavailable": "இந்த CLI புதுப்பிப்புச் சோதனையை ஆதரிக்கவில்லை.",
  },
  uk: {
    "updates.title": "Оновлення застосунку та CLI", "updates.app": "Десктопний застосунок", "updates.cli": "Supercharge CLI", "updates.notChecked": "Не перевірено", "updates.current": "Актуальна версія", "updates.notPublished": "Десктопний випуск ще не опубліковано", "updates.available": "Доступне оновлення", "updates.downloading": "Завантаження…", "updates.downloaded": "Завантажено · перезапустіть для застосування", "updates.installing": "Установлення…", "updates.installed": "Установлено · перезапустіть для використання", "updates.manual": "Потрібне ручне встановлення", "updates.failed": "Помилка оновлення", "updates.restartReady": "Оновлення готові до перезапуску", "updates.checking": "Перевірка обох версій…", "updates.restartHint": "Перезапустіть, коли будете готові. До того часу чати продовжують працювати.", "updates.description": "Оновлює застосунок і CLI лише до новіших версій. Перевірені завантаження зберігаються для повторного використання.", "updates.check": "Перевірити застосунок і CLI", "updates.updateBoth": "Оновити застосунок і CLI", "updates.restart": "Перезапустити для застосування оновлень", "updates.restarting": "Перезапуск…", "updates.openDownload": "Завантажити інсталятор застосунку", "updates.confirmTitle": "Перезапустити для застосування оновлень?", "updates.confirmBody": "Завантажене оновлення буде застосовано, і Supercharge перезапуститься. Поточні завдання агентів зупиняться; збережені чати залишаться.",
    "updates.cliMissing": "Supercharge CLI не встановлено.",
    "updates.cliCheckUnavailable": "Ця CLI не підтримує перевірку оновлень.",
  },
  zh: {
    "updates.title": "应用与 CLI 更新", "updates.app": "桌面应用", "updates.cli": "Supercharge CLI", "updates.notChecked": "尚未检查", "updates.current": "已是最新", "updates.notPublished": "尚未发布桌面版本", "updates.available": "有可用更新", "updates.downloading": "正在下载…", "updates.downloaded": "已下载 · 重启后应用", "updates.installing": "正在安装…", "updates.installed": "已安装 · 重启后使用", "updates.manual": "需要手动安装", "updates.failed": "更新失败", "updates.restartReady": "更新已就绪，可以重启", "updates.checking": "正在检查两个版本…", "updates.restartHint": "准备好后再重启，在此之前当前对话会继续运行。", "updates.description": "仅更新到较新的应用和 CLI 版本，已验证的下载会保留以供复用。", "updates.check": "检查应用与 CLI", "updates.updateBoth": "更新应用与 CLI", "updates.restart": "重启以使用更新", "updates.restarting": "正在重启…", "updates.openDownload": "下载应用安装包", "updates.confirmTitle": "重启以使用更新？", "updates.confirmBody": "将应用已下载的更新并重启 Supercharge。正在运行的智能体任务会停止，已保存的对话会保留。",
    "updates.cliMissing": "尚未安装 Supercharge CLI。",
    "updates.cliCheckUnavailable": "当前 CLI 不支持更新检查。",
  },
  "zh-TW": {
    "updates.title": "應用程式與 CLI 更新", "updates.app": "桌面應用程式", "updates.cli": "Supercharge CLI", "updates.notChecked": "尚未檢查", "updates.current": "已是最新", "updates.notPublished": "尚未發布桌面版本", "updates.available": "有可用更新", "updates.downloading": "正在下載…", "updates.downloaded": "已下載 · 重新啟動後套用", "updates.installing": "正在安裝…", "updates.installed": "已安裝 · 重新啟動後使用", "updates.manual": "需要手動安裝", "updates.failed": "更新失敗", "updates.restartReady": "更新已就緒，可以重新啟動", "updates.checking": "正在檢查兩個版本…", "updates.restartHint": "準備好後再重新啟動，在此之前目前的對話會繼續執行。", "updates.description": "僅更新至較新的應用程式和 CLI 版本，已驗證的下載會保留供重複使用。", "updates.check": "檢查應用程式與 CLI", "updates.updateBoth": "更新應用程式與 CLI", "updates.restart": "重新啟動以使用更新", "updates.restarting": "正在重新啟動…", "updates.openDownload": "下載應用程式安裝程式", "updates.confirmTitle": "重新啟動以使用更新？", "updates.confirmBody": "將套用已下載的更新並重新啟動 Supercharge。執行中的代理程式工作會停止，已儲存的對話會保留。",
    "updates.cliMissing": "尚未安裝 Supercharge CLI。",
    "updates.cliCheckUnavailable": "目前 CLI 不支援更新檢查。",
  },
} satisfies Record<string, Updates>;
