import type { SettingsEntry } from "../types";

/** Settings catalog entries — provider configuration. */
export const ACCOUNT_ENTRIES: readonly SettingsEntry[] = [
  {
    id: "account.providers",
    section: "account",
    tab: "providers",
    anchorId: "settings-anchor-account-providers",
    labelKey: "settings.tabProviders",
    descKeys: [
      "settings.tabProvidersHint",
      "prov.appendPromptHint",
      "prov.supportsVisionHint",
      "prov.mode.genericHint",
    ],
    keywords: [
      "provider",
      "relay",
      "custom api",
      "base url",
      "api format",
      "chat completions",
      "responses",
      "messages",
      "append prompt",
      "system prompt",
      "rules",
      "vision",
      "image",
      "中转",
      "中轉",
      "提供商",
      "供應商",
      "看图",
      "看圖",
    ],
  },
  {
    id: "account.providers.extraHeaders",
    section: "account",
    tab: "providers",
    anchorId: "settings-anchor-prov-extra-headers",
    labelKey: "prov.extraHeaders",
    descKeys: ["prov.extraHeadersHint"],
    keywords: [
      "extra headers",
      "custom headers",
      "user-agent",
      "originator",
      "x-api-key",
      "自定义请求头",
      "自訂請求標頭",
      "請求頭",
    ],
  },
  {
    id: "account.providers.supportsVision",
    section: "account",
    tab: "providers",
    anchorId: "settings-anchor-prov-supports-vision",
    labelKey: "prov.supportsVision",
    descKeys: ["prov.supportsVisionHint"],
    keywords: [
      "vision",
      "image_url",
      "see images",
      "multimodal",
      "video",
      "context window",
      "看图",
      "看圖",
      "识图",
      "識圖",
      "视频",
      "影片",
      "上下文",
    ],
  },
  {
    id: "account.providers.mode",
    section: "account",
    tab: "providers",
    anchorId: "settings-anchor-provider-mode",
    labelKey: "prov.mode",
    descKeys: ["prov.mode.genericHint"],
    keywords: [
      "provider mode",
      "api backend",
      "chat completions",
      "responses",
      "anthropic messages",
      "提供商模式",
      "供應商模式",
      "接口格式",
      "介面格式",
    ],
  },
];
