import type { SettingsEntry } from "../types";

export const PET_ENTRIES: readonly SettingsEntry[] = [
  {
    id: "pet.companion",
    section: "pet",
    tab: "look",
    anchorId: "settings-anchor-pet",
    labelKey: "settings.nav.pet",
    descKeys: [
      "settings.pet.desc",
      "settings.pet.enabled",
      "settings.pet.enabledDesc",
      "settings.tab.petLook",
    ],
    keywords: [
      "pet",
      "宠物",
      "寵物",
      "desktop pet",
      "companion",
      "overlay",
      "mascot",
      "外观设置",
      "外觀設定",
    ],
  },
  {
    id: "pet.bubbles",
    section: "pet",
    tab: "bubbles",
    anchorId: "settings-anchor-pet-bubbles",
    labelKey: "settings.pet.bubbles",
    descKeys: ["settings.pet.bubblesDesc", "settings.tab.petBubbles"],
    keywords: [
      "bubble",
      "bubbles",
      "tips",
      "提示框",
      "气泡",
      "氣泡",
      "chip",
      "stage",
      "阶段性",
      "气泡设置",
      "氣泡設定",
    ],
  },
  {
    id: "pet.progressBar",
    section: "pet",
    tab: "bubbles",
    anchorId: "settings-anchor-pet-progress",
    labelKey: "settings.pet.progressBar",
    descKeys: ["settings.pet.progressBarDesc"],
    keywords: ["progress", "bar", "进度条", "進度條", "loading"],
  },
  {
    id: "pet.bubbleDismiss",
    section: "pet",
    tab: "bubbles",
    anchorId: "settings-anchor-pet-dismiss",
    labelKey: "settings.pet.bubbleDismiss",
    descKeys: ["settings.pet.bubbleDismissDesc", "settings.pet.bubbleDismiss.seconds"],
    keywords: ["dismiss", "timeout", "seconds", "自动关闭", "自動關閉", "15"],
  },
  {
    id: "pet.bubbleLook",
    section: "pet",
    tab: "bubbles",
    anchorId: "settings-anchor-pet-bubble-look",
    labelKey: "settings.pet.bubbleLook",
    descKeys: [
      "settings.pet.bubbleLookDesc",
      "settings.pet.bubbleShape",
      "settings.pet.bubbleStyle",
    ],
    keywords: [
      "shape",
      "background",
      "glass",
      "paper",
      "气泡形状",
      "氣泡形狀",
      "背景",
    ],
  },
  {
    id: "pet.identity",
    section: "pet",
    tab: "look",
    anchorId: "settings-anchor-pet-identity",
    labelKey: "settings.pet.identity",
    descKeys: [
      "settings.pet.identityDesc",
      "settings.pet.shape",
      "settings.pet.expression",
      "settings.pet.color",
      "settings.pet.eyeColor",
    ],
    keywords: [
      "shape",
      "color",
      "avatar",
      "hex",
      "blob",
      "expression",
      "face",
      "cloud",
      "teardrop",
      "形状",
      "形态",
      "表情",
      "颜色",
      "眼睛",
      "eyes",
    ],
  },
  {
    id: "pet.expression",
    section: "pet",
    tab: "look",
    anchorId: "settings-anchor-pet-expression",
    labelKey: "settings.pet.expression",
    descKeys: ["settings.pet.expressionDesc"],
    keywords: [
      "expression",
      "face",
      "mood",
      "表情",
      "rest",
      "happy",
      "angry",
    ],
  },
  {
    id: "pet.eyeColor",
    section: "pet",
    tab: "look",
    anchorId: "settings-anchor-pet-eye",
    labelKey: "settings.pet.eyeColor",
    descKeys: ["settings.pet.eyeColorDesc", "settings.pet.eyeColor.auto"],
    keywords: [
      "eyes",
      "eye color",
      "black",
      "white",
      "contrast",
      "眼睛",
      "眼珠",
      "眼色",
      "黑色",
      "白色",
    ],
  },
  {
    id: "pet.size",
    section: "pet",
    tab: "look",
    anchorId: "settings-anchor-pet-size",
    labelKey: "settings.pet.size",
    descKeys: ["settings.pet.sizeDesc"],
    keywords: ["size", "scale", "尺寸", "大小"],
  },
];
